# Generated by Django 4.2.2 on 2023-07-02 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kanban.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доска',
                'verbose_name_plural': 'Доски',
            },
            bases=(models.Model, kanban.models.DateStempMixin),
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Название')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.board', verbose_name='Доска')),
            ],
            options={
                'verbose_name': 'Колонка',
                'verbose_name_plural': 'Колонки',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.column', verbose_name='Колонка')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['position'],
            },
            bases=(models.Model, kanban.models.DateStempMixin),
        ),
    ]
