# Generated by Django 4.2.2 on 2023-07-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='title',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Название'),
        ),
    ]
